[package]
name = "raytracer"
version = "0.1.0"
authors = ["Christian Briones <cwbriones@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
image = "0.23"
crossbeam = "0.8"
argh = "0.1"

[profile.release]
# lto = true
